<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Mono.Cecil" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FarmTogether2.ContractModel/FarmTogether2.ContractModel.csproj" />
    <ProjectReference Include="../../src/Stubs/Assembly-CSharp/Assembly-CSharp.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../tools/FarmTogether2.ModKit.Tool/FarmTogether2.ModKit.Tool.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/Il2Cppmscorlib/Il2Cppmscorlib.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/MilkstoneUnityExtensions/MilkstoneUnityExtensions.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/UnityEngine.IMGUIModule/UnityEngine.IMGUIModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/UnityEngine.InputLegacyModule/UnityEngine.InputLegacyModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Stubs/UnityEngine.TextRenderingModule/UnityEngine.TextRenderingModule.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
