<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>FarmTogether2.GameApi.Ref</PackageId>
    <Version>1.0.1</Version>
    <Authors>Abmcar</Authors>
    <Description>Compile-time references for supported Farm Together 2 mod builds.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Stubs/Assembly-CSharp/Assembly-CSharp.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/Il2Cppmscorlib/Il2Cppmscorlib.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/MilkstoneUnityExtensions/MilkstoneUnityExtensions.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/UnityEngine.CoreModule/UnityEngine.CoreModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/UnityEngine.IMGUIModule/UnityEngine.IMGUIModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/UnityEngine.InputLegacyModule/UnityEngine.InputLegacyModule.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Stubs/UnityEngine.TextRenderingModule/UnityEngine.TextRenderingModule.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../Stubs/Assembly-CSharp/bin/$(Configuration)/net6.0/Assembly-CSharp.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/Il2Cppmscorlib/bin/$(Configuration)/net6.0/Il2Cppmscorlib.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/MilkstoneUnityExtensions/bin/$(Configuration)/net6.0/MilkstoneUnityExtensions.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/UnityEngine.CoreModule/bin/$(Configuration)/net6.0/UnityEngine.CoreModule.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/UnityEngine.IMGUIModule/bin/$(Configuration)/net6.0/UnityEngine.IMGUIModule.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/UnityEngine.InputLegacyModule/bin/$(Configuration)/net6.0/UnityEngine.InputLegacyModule.dll" Pack="true" PackagePath="ref/net6.0" />
    <None Include="../Stubs/UnityEngine.TextRenderingModule/bin/$(Configuration)/net6.0/UnityEngine.TextRenderingModule.dll" Pack="true" PackagePath="ref/net6.0" />
  </ItemGroup>
</Project>
