<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FarmTogether2.ModKit.Tool</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Cecil" />
    <PackageReference Include="NuGet.Packaging" />
  </ItemGroup>
</Project>
